### ISSUE TITLE
Different default output directories for Windows and Mac

### ISSUE THREAD

**Issue by grahammcculloch** [mseag/bible-karaoke#112]
As per [this comment](https://github.com/sillsdev/bible-karaoke/pull/108#discussion_r484208632) it would probably be better to default to the user's home directory for Mac but to the Videos directory for Windows.

e.g. 
```javascript
const BK_DIR_NAME = 'Bible Karaoke Videos';

export const getDefaultOutputDirectory = () => {
  switch (process.platform) {
    case 'win32':
      return path.join(os.homedir(), 'Videos', BK_DIR_NAME );
    case 'darwin':
    default:
      return path.join(os.homedir(), BK_DIR_NAME );
  }
}
```

TBD: Do we need to account for different paths for older versions of Windows?

**Comment by megahirt** [comment]
@grahammcculloch yes to supporting Windows 7/8/10.

Could also throw in a `case 'linux':` but it's a moot point right now since the default would be correct for linux AFAIK.

**Comment by megahirt** [comment]
For Windows 8/10 we should use:
```
return path.join(os.homedir(), 'Videos', BK_DIR_NAME );
```
For Windows 7 we should use:
```
return path.join(os.homedir(), 'My Videos', BK_DIR_NAME );
```
We won't support XP/Vista.

Windows 7 home directory looks something like this:
![image](https://user-images.githubusercontent.com/3444521/92359418-6b98ba80-f115-11ea-98f1-cdcef7297c9b.png)

To determine the windows version, use [os.release](https://nodejs.org/api/os.html#os_os_release) and compare against these strings:
![image](https://user-images.githubusercontent.com/3444521/92359700-e4981200-f115-11ea-92bc-4cfa6e4efccd.png)
See https://stackoverflow.com/a/44916050
