### ISSUE TITLE
Create integration tests for rendered images

### ISSUE THREAD

**Issue by megahirt** [mseag/bible-karaoke#176]
Our current tests do not actually test the output of images to ensure that text and background are correctly rendered in our process.  The tests that we do have are more like "smoke tests" that simply exercise the code and fail if there is an error.

This issue is about writing actual tests that do image comparison to verify that our code produces the expected images.

@jamesduncan suggested looking into [puppeteer-screenshot-tester](https://www.npmjs.com/package/puppeteer-screenshot-tester) since we already have puppeteer as a dev dependency.

**Comment by jamesduncan** [comment]
I am going to first look at building the test using this library. https://github.com/mapbox/pixelmatch 

My goal will be to determine if the images generated at various times of the video are the same or different. We will assume that if they are different the animation script is at the minimum outputting changing images over time. It may require an individual to look at the final video to truly determine if the animation scripts are working properly.
