### ISSUE TITLE
Clean up Babel / Typescript compilation chain

### ISSUE THREAD

**Issue by megahirt** [mseag/bible-karaoke#186]
Now that we have moved to 100% TypeScript for the front-end React and back-end Electron Node.JS code, we should in theory no longer need babel for transpilation and can rely on `tsc` for JS compilation.

An undesirable symptom of having both babel and tsc involved is that we currently have 4 tsconfig.json files, with the base config being tsconfig.spec.json

Reducing the number of tsconfig files down to 2 or 3 should be possible after removing the babel compilation step from the react scripts / webpack piece.

IJH: This example repo is most helpful to our toolchain needs: https://github.com/yhirose/react-typescript-electron-sample-with-create-react-app-and-electron-builder

**Comment by irahopkinson** [comment]
We are more likely to want to replace the existing rescripts (package that sits over the react scripts framework) babel compiler with TSC.

**Comment by irahopkinson** [comment]
@wongpratan we want to remove `@rescripts/cli` because it has been deprecated for some time and now archived!
Some options are listed here https://www.electronjs.org/docs/latest/tutorial/boilerplates-and-clis
We are already using `electron-builder` so that could be a good place to start with its [boilerplates](https://www.electron.build/#boilerplates), in particular the [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate) looks good.

**Comment by irahopkinson** [comment]
I just looked through all our vulnerabilities as reported here by GH. There are 16 = 1 critical + 4 high + 9 moderate + 2 low. They are _all_ caused by our dependency on `@rescripts/cli`.

**Comment by irahopkinson** [comment]
I have a working production build and developer build (with hot reload) on branch `task/removeRescripts` but the frontend (`npm start`) has 4 complier warnings like this:

> WARNING in ./node_modules/electron-ga-uuid/lib/consts.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\Ira\src\bible-karaoke\node_modules\electron-ga-uuid\src\consts.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\Ira\src\bible-karaoke\node_modules\electron-ga-uuid\src\consts.ts'
 @ ./node_modules/electron-ga-uuid/lib/index.js 44:17-36
 @ ./src/App/analytics.ts 3:0-66 17:26-39 68:22-37
 @ ./src/App/components/Analytics.tsx 10:0-37 14:17-26 22:41-50
 @ ./src/index.tsx 9:0-63 23:35-52

According to [this issue 11767](https://github.com/facebook/create-react-app/discussions/11767), these are correct warnings and we need to either include the source or not include source maps.

**Comment by irahopkinson** [comment]
This PR https://github.com/nh758/electron-ga-uuid/pull/4 should fix this ^^.
