### ISSUE TITLE
Audio and Highlighting are out by one

### ISSUE THREAD

**Issue by JCFarrow** [mseag/bible-karaoke#202]
When I render Naya Ephesians 1 there is no audio for the first section (heading?) so the audio is reading one verse ahead of the highlighting.

**Comment by JCFarrow** [comment]
The problem is that the audio files for Naya Ephesians 1 are named wrong (0, 1, 2... instead of 1, 2, 3... with the first section skipped)

I opened HearThis to see if that was where the problem is. But in all my tests (recording audio, deleting audio, skipping sections) the files were still named correctly (skipping the numbers where there is no audio).

So my thought now is that this issue must be a problem with the sample project (Naya) and not BibleKaraoke. Either it was made in an older version of HearThis that did not work as expected, or the audio files got renamed somehow.

**Comment by irahopkinson** [comment]
Asked for some new sample data to confirm this diagnosis.

**Comment by JCFarrow** [comment]
This is a problem with the sample data. The whole book of Ephesians needs the audio files renamed with +1.
This is not an issue with BK so I've closed it.
