### ISSUE TITLE
Support Scripture App Builder as an input program

### ISSUE THREAD

**Issue by megahirt** [mseag/bible-karaoke#21]
Bible Karaoke should detect the presence of Scripture App Builder (SAB) projects on the computer and offer to render a video for those projects present that have audio and timing files.

**Comment by rdai** [comment]
https://gist.github.com/rdai/c61f8059f78a1675d41b2ba31b191450

this is what I have so far. You need to create a SABAssets folder under root, and this has hard coded to look for a "1.appDef" in the root. This will be replaced with dynamic values once integrated. This also is assuming working off a project with correct FCBH streaming audio defined.

The output is SABAssets/1.mp3 for consumption.

I will work on getting the corresponding SAB chapter to be outputted to the same working folder: SABAssets.

**Comment by rdai** [comment]
gist updated, now can successfully download both mp3 and build the XML for the chapter, need to configure some parameters to be integrated into the actual project.

**Comment by megahirt** [comment]
This issue represents a major project goal represented by the version 1.0 milestone.  This issue isn't actionable given how broad this is, so I will close this issue.
