### ISSUE TITLE
Migrate AppState data from the old store

### ISSUE THREAD

**Issue by irahopkinson** [mseag/bible-karaoke#76]
#74 changes to using `mobx-persist` for persisting data. It would be a better UX if we migrated AppState data from the old store if it exists.

**Comment by grahammcculloch** [comment]
Added in ui v2.

The 'old' localStorage keys are deleted after migration. So the migration will only run once and will be skipped on following application starts.

**Comment by irahopkinson** [comment]
This looks like it is done. We just need to to test that it is. Clear all data in the new settings store (as used on `master`), run up v0.3.6 and change all the settings to known values. Run the current `master` and check all those known values are still there (have been migrated).

**Comment by iamam34** [comment]
Steps to test:
1. Clear current settings
```sh
git checkout master # v1.0.0 RC
nvm use 16.9.0
npm i
npm run electron-dev
# reset [speechbubble, text, background, textLocation] settings to default via UI
# close application
```
2. Run v0.3.6 and set settings to known values (not default values)
```sh
git checkout release/v0.3.6
rm -rf node_modules # fixes node-gyp tangle
nvm use 12.21.0
npm i
npm run electron-dev
# set speechbubble, text, background, textLocation
# close application
```
3. Run v1.0.0 and verify those settings are carried across
```sh
git checkout master # v1.0.0 RC
nvm use 16.9.0
npm i
npm run electron-dev
# verify the settings are not default
```

**Comment by iamam34** [comment]
Yes - can confirm my custom values for [speechbubble, background, text, textLocation] are migrated to v1.0.0 and persisted to the next application session. The migration works!
