### ISSUE TITLE
Add link to license in the Settings drawer

### ISSUE THREAD

**Issue by irahopkinson** [mseag/bible-karaoke#79]
In the Settings drawer, add a link to our license on GitHub: https://github.com/sillsdev/bible-karaoke/blob/master/LICENSE.md, e.g. "This software is released under the MIT License" and link to "MIT License". And add the text "This software uses libraries from the FFmpeg project under the LGPLv2.1".

**Comment by grahammcculloch** [comment]
Added to UI v2

**Comment by irahopkinson** [comment]
Done in the current master. Tested by @JCFarrow.
