### ISSUE TITLE
Research alternative XML library for SAB support

### ISSUE THREAD

**Issue by nh758** [mseag/bible-karaoke#86]
The node libraries use python

**Comment by nh758** [comment]
Concluded that JSDOM is likely the best replacement for the libxml dependency.  This supports an XML document input. SAB parsing code will need to be rewritten to use DOM style queries instead of xpath.

**Comment by rdai** [comment]
I think Ira already did this in the code.

**Comment by irahopkinson** [comment]
Branch `feature/SABdraft` is already using `jsdom`.
