### ISSUE TITLE
Provide a mechanism to render the entire book or multiple chapters into one video

### ISSUE THREAD

**Issue by megahirt** [mseag/bible-karaoke#9]
Perhaps we could change the UI from using dropdowns to using a more complex selector (range slider or something) to select more than one chapter at a time.

**Comment by grahammcculloch** [comment]
@wongpratan [this line](https://github.com/sillsdev/bible-karaoke/blob/5c6391ab4db6085152f7418d928e9af414c7d1e6/public/karaoke.js#L13) currently accepts a single `hearThisFolder`. But we pass this straight into an array [here](https://github.com/sillsdev/bible-karaoke/blob/5c6391ab4db6085152f7418d928e9af414c7d1e6/public/karaoke.js#L25). So it might be a very simple change to support multiple folder paths! Can you try and 'test' this by calling the `bbkConvert` method with an array of more than one folder as the `_` argument to the `bbkConvert` method? Hopefully that will generate one video with multiple input chapters!

**Comment by wongpratan** [comment]
@grahammcculloch I tested to pass an array with 2 path strings by hard code. it generates the same result with the first path. I think it uses only first path [there](https://github.com/sillsdev/bible-karaoke/blob/5c6391ab4db6085152f7418d928e9af414c7d1e6/public/cli/lib/commands/convert.js#L124).

**Comment by grahammcculloch** [comment]
@wongpratan are you able to investigate converting the underlying code to process all the items in that array?

**Comment by wongpratan** [comment]
@grahammcculloch I used $ ffmpeg to test to combine our 5 chapter video files. It is so quick to combine. It spends less than 2 seconds. 

`$ ffmpeg -f concat -safe 0 -i mylist.txt -c copy output.mp4`
[concat demuxer](https://stackoverflow.com/questions/7333232/how-to-concatenate-two-mp4-files-using-ffmpeg#answer-11175851)

**Comment by megahirt** [comment]
#87 implements this feature.
