### ISSUE TITLE
Organize public sample data for SAB

### ISSUE THREAD

**Issue by megahirt** [mseag/bible-karaoke#93]
Acquire some sample data for SAB from various projects with various scripts

**Comment by irahopkinson** [comment]
I created a PT project and here is a small test data set https://drive.google.com/drive/folders/1BU2XII1KOQNyJSrsmg3DgL3PNcXT38aN?usp=sharing

**Comment by megahirt** [comment]
We now theoretically have 5 SAB datasets in the Google drive folder for developers to use.  In the future, we could perhaps use pieces of these datasets as part of unit or integration tests, checking in the component of SAB that is required for the method under test.

**Comment by megahirt** [comment]
I am satisfied with our SAB test projects for now.  Closing this issue.
