### ISSUE TITLE
temp frame_nnn.png files are not deleted after video is rendered

### ISSUE THREAD

**Issue by hahn-kev** [mseag/bible-karaoke#98]
From what I can tell we don't delete the image files after the video is rendered. Something we should probably fix eventually.

**Comment by echu888** [comment]
[A current pull request](https://github.com/sindresorhus/tempy/pull/25) to the tempy package that we're using may help to facilitate the clean-up.

**Comment by Richienb** [comment]
The pull request is now merged!

**Comment by irahopkinson** [comment]
Fixed in PR #190 (issue #177).
